font_family      Maple Mono NF
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

disable_ligatures never

repaint_delay        6
input_delay          2
sync_to_monitor      yes
resize_draw_strategy static

cursor_shape         beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0

cursor_trail         3
cursor_trail_decay   0.1 0.4

scrollback_lines         10000
wheel_scroll_multiplier  3.0
touch_scroll_multiplier  3.0

window_padding_width     8 12
background_opacity       1
dynamic_background_opacity no
hide_window_decorations  no
confirm_os_window_close  0

enable_audio_bell        no

foreground #d7cdb2
background #15140f
cursor     #d0be76
selection_foreground #15140f
selection_background #2f2e27

color0  #201f1a
color1  #c26f5c
color2  #89ad70
color3  #d3a269
color4  #6a8896
color5  #8e7696
color6  #6aa7a2
color7  #aba492
color8  #6f6c63
color9  #e8866f
color10 #a1cb82
color11 #d0be76
color12 #78a6bb
color13 #af8db9
color14 #77c6c1
color15 #d7cdb2
